name: Setup CI/CD and Tools for AI & Web Dev

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Building and deploying web application
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Build and Deploy
      run: |
        npm run build
        npm run deploy
