name: Setup CI/CD and Tools for AI & Web Dev

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setting up Python environment for AI development
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Running tests
    - name: Run tests
      run: |
        pytest

    # Building and deploying web application
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Build and Deploy
      run: |
        npm run build
        npm run deploy
